export const FIREBASE_CONST = {
    // USER PROPERTIES
    USER_ID: 'USER_ID',
    USER_NAME: 'USER_NAME',
    USER_ABOUT: 'USER_ABOUT',
    USER_MIN_AGE: 'USER_MIN_AGE',
    USER_MAX_AGE: 'USER_MAX_AGE',
    USER_FILTER_APPLIED: 'FILTER_APPLIED',
    USER_AGE_GROUP: 'AGE_GROUP',
    USER_MOOD: 'MOOD',
    
    //PARAMS
    LOGIN_TIME: 'LOGIN_TIME',
    LOGOUT_TIME: 'LOGOUT_TIME',

    //EVENTS
    LOGIN_EVENT: 'LOGIN_EVENT',
    LOG_OUT_EVENT: 'LOG_OUT_EVENT'
};
