export const asyncStorageKeys = {
    USER_ID: 'USER_ID',
    USER_NAME: 'USER_NAME',
    USER_TOKEN: 'USER_TOKEN',
    DEVICE_TOKEN: 'DEVICE_TOKEN',
    IS_USER_LOGIN: 'IS_USER_LOGIN',
    USER_PHONE_UNIQ_ID: 'USER_PHONE_UNIQ_ID'
    
};
